spring.application.name=BookManageApplication
spring.devtools.restart.enabled=false
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:demo-data.sql
spring.datasource.url=jdbc:h2:mem:bookdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=